const ERROR_VALIDATION = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_DEFAULT = 500;
const OK = 200;
const UNAUTHORIZED = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_CONFLICT = 409;
const CREATED = 201;

module.exports = {
  ERROR_VALIDATION,
  ERROR_NOT_FOUND,
  ERROR_DEFAULT,
  OK,
  UNAUTHORIZED,
  ERROR_FORBIDDEN,
  ERROR_CONFLICT,
  CREATED,
};
